### ISSUE TITLE
Not working on Landscape Mode

### ISSUE THREAD

**Issue by Joel619** [WebsiteBeaver/capacitor-document-scanner#5] opened 2022-08-09 01:45 UTC
When the device is in Landscape mode it crashes the app.

**Comment by dmarcs** [comment] 2022-08-10 14:36
What error message did you get? It works for me in Landscape mode. I'm using a Pixel.

**Comment by Joel619** [comment] 2022-08-10 20:27
> What error message did you get? It works for me in Landscape mode. I'm using a Pixel.

Im using a Samsung Galaxy Tab S6 and a Samsung Galaxy S22 Ultra (both physical) to make some test but it just crashes and closes the app. Haven't test it on debug mode to check if there's any error log but will check that and post back.

**Comment by brunobless** [comment] 2022-09-06 13:38
First of all, thank you for the great work of capacitor-plugin!

I have also noticed the behaviour described here from time to time on some Android devices. It seems to happen when the "OpenCV" library cannot be loaded (Error: Cannot load info library for OpenCV).

Reproduction steps:
1.) Start the scan process
2.) Scan a document (portrait or landscape format doesn't matter)
3) In the preview view, hold the smartphone in landscape format.
4) Click on confirm (OK check mark)
5) The camera opens again (two on top of each other) and the previous scan is discarded.

### The following errors are displayed in the debug console:
**E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV**
D/OpenCV/StaticHelper: Library list: ""
D/OpenCV/StaticHelper: First attempt to load libs
D/OpenCV/StaticHelper: Trying to init OpenCV libs
D/OpenCV/StaticHelper: Trying to load library opencv_java4
D/OpenCV/StaticHelper: Library opencv_java4 loaded
D/OpenCV/StaticHelper: First attempt to load libs is OK
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper: General configuration for OpenCV 4.5.5 =====================================
I/OpenCV/StaticHelper:   Version control:               4.5.5
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Platform:
I/OpenCV/StaticHelper:     Timestamp:                   2021-12-25T07:49:23Z
I/OpenCV/StaticHelper:     Host:                        Linux 4.4.0-210-generic x86_64
I/OpenCV/StaticHelper:     Target:                      Android 1 aarch64
I/OpenCV/StaticHelper:     CMake:                       3.6.0-rc2
I/OpenCV/StaticHelper:     CMake generator:             Ninja
I/OpenCV/StaticHelper:     CMake build tool:            /opt/android/android-sdk.gradle/cmake/3.6.4111459/bin/ninja
I/OpenCV/StaticHelper:     Configuration:               Release
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   CPU/HW features:
I/OpenCV/StaticHelper:     Baseline:                    NEON FP16
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   C/C++:
I/OpenCV/StaticHelper:     Built as dynamic libs?:      NO
I/OpenCV/StaticHelper:     C++ standard:                11
I/OpenCV/StaticHelper:     C++ Compiler:                /opt/android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  (ver 7.0)
I/OpenCV/StaticHelper:     C++ flags (Release):         -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden  -O2 -DNDEBUG   -DNDEBUG
I/OpenCV/StaticHelper:     C++ flags (Debug):           -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden  -O0 -fno-limit-debug-info   -DDEBUG -D_DEBUG -g
I/OpenCV/StaticHelper:     C Compiler:                  /opt/android/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
I/OpenCV/StaticHelper:     C flags (Release):           -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden  -O2 -DNDEBUG   -DNDEBUG
I/OpenCV/StaticHelper:     C flags (Debug):             -isystem /opt/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden  -O0 -fno-limit-debug-info   -DDEBUG -D_DEBUG -g
I/OpenCV/StaticHelper:     Linker flags (Release):      -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /opt/android/android-ndk-r18b/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/opt/android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now   -Wl,--as-needed  
I/OpenCV/StaticHelper:     Linker flags (Debug):        -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /opt/android/android-ndk-r18b/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/opt/android/android-ndk-r18b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now   -Wl,--as-needed  
I/OpenCV/StaticHelper:     ccache:                      YES
I/OpenCV/StaticHelper:     Precompiled headers:         NO
I/OpenCV/StaticHelper:     Extra dependencies:          z dl m log
I/OpenCV/StaticHelper:     3rdparty dependencies:       libcpufeatures libprotobuf ade tbb ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf quirc tegra_hal
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   OpenCV modules:
I/OpenCV/StaticHelper:     To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc java ml objdetect photo stitching video videoio
I/OpenCV/StaticHelper:     Disabled:                    world
I/OpenCV/StaticHelper:     Disabled by dependency:      -
I/OpenCV/StaticHelper:     Unavailable:                 python2 python3 ts
I/OpenCV/StaticHelper:     Applications:                -
I/OpenCV/StaticHelper:     Documentation:               NO
I/OpenCV/StaticHelper:     Non-free algorithms:         NO
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Android NDK:                   /opt/android/android-ndk-r18b (ver 18.1.5063045)
I/OpenCV/StaticHelper:     Android ABI:                 arm64-v8a
I/OpenCV/StaticHelper:     NDK toolchain:               aarch64-linux-android-clang
I/OpenCV/StaticHelper:     STL type:                    c++_shared
I/OpenCV/StaticHelper:     Native API level:            21
I/OpenCV/StaticHelper:   Android SDK:                   /opt/android/android-sdk.gradle (tools: 26.1.1 build tools: 28.0.3)
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   GUI:                           NONE
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Media I/O: 
I/OpenCV/StaticHelper:     ZLib:                        z (ver 1.2.7)
I/OpenCV/StaticHelper:     JPEG:                        build-libjpeg-turbo (ver 2.1.2-62)
I/OpenCV/StaticHelper:     WEBP:                        build (ver encoder: 0x020f)
I/OpenCV/StaticHelper:     PNG:                         build (ver 1.6.37)
I/OpenCV/StaticHelper:     TIFF:                        build (ver 42 - 4.2.0)
I/OpenCV/StaticHelper:     JPEG 2000:                   build (ver 2.4.0)
I/OpenCV/StaticHelper:     OpenEXR:                     build (ver 2.3.0)
I/OpenCV/StaticHelper:     HDR:                         YES
I/OpenCV/StaticHelper:     SUNRASTER:                   YES
I/OpenCV/StaticHelper:     PXM:                         YES
I/OpenCV/StaticHelper:     PFM:                         YES
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Video I/O:
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Parallel framework:            TBB (ver 2020.2 interface 11102)
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Trace:                         YES (with Intel ITT)
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Other third-party libraries:
I/OpenCV/StaticHelper:     Custom HAL:                  YES (carotene (ver 0.0.1))
I/OpenCV/StaticHelper:     Protobuf:                    build (3.19.1)
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Python (for build):            /usr/bin/python2.7
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Java:                          export all functions
I/OpenCV/StaticHelper:     ant:                         NO
I/OpenCV/StaticHelper:     Java wrappers:               YES
I/OpenCV/StaticHelper:     Java tests:                  NO
I/OpenCV/StaticHelper: 
I/OpenCV/StaticHelper:   Install to:                    /build/master_pack-android/build/o4a/install
I/OpenCV/StaticHelper: -----------------------------------------------------------------
D/HiTouch_PressGestureDetector: onAttached, package=ch.proffix.qrscanner, windowType=1, mHiTouchRestricted=false
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/libEGL: EGLNativeWindowType 0x6fa172e750 disconnect failed
D/ZrHung.AppEyeUiProbe: not watching, wait.
D/ActivityThread: Remove activity client record, r= ActivityRecord{bc4ffcc token=android.os.BinderProxy@7b5494b {ch.proffix.qrscanner/com.websitebeaver.documentscanner.DocumentScannerActivity}} token= android.os.BinderProxy@7b5494b
D/ZrHung.AppEyeUiProbe: restart watching
V/ActivityThread: callActivityOnCreate
W/ContextImpl: Failed to ensure /storage/6161-3566/Android/data/ch.proffix.qrscanner/files/Pictures: java.lang.IllegalStateException: Failed to prepare /storage/6161-3566/Android/data/ch.proffix.qrscanner/files/Pictures/: android.os.ServiceSpecificException:  (code -30)
D/ActivityThread: add activity client record, r= ActivityRecord{bc4ffcc token=android.os.BinderProxy@7b5494b {ch.proffix.qrscanner/com.websitebeaver.documentscanner.DocumentScannerActivity}} token= android.os.BinderProxy@7b5494b
**E/cv::error(): OpenCV(4.5.5) Error: Assertion failed (!_src.empty()) in cvtColor, file /build/master_pack-android/opencv/modules/imgproc/src/color.cpp, line 182
E/org.opencv.imgproc: imgproc::cvtColor_11() caught cv::Exception: OpenCV(4.5.5) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'**
I/BlockMonitor: dispatchingThrewException In MainThread
D/AndroidRuntime: Shutting down VM
I/QarthLog: [PatchStore] createDisableExceptionQarthFile
I/QarthLog: [PatchStore] create disable file for ch.proffix.qrscanner uid is 10328
**E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ch.proffix.qrscanner, PID: 24319
    java.lang.RuntimeException: Unable to resume activity {ch.proffix.qrscanner/com.websitebeaver.documentscanner.DocumentScannerActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1040250175, result=-1, data=null} to activity {ch.proffix.qrscanner/com.websitebeaver.documentscanner.DocumentScannerActivity}: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
    ]
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4789)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4832)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1040250175, result=-1, data=null} to activity {ch.proffix.qrscanner/com.websitebeaver.documentscanner.DocumentScannerActivity}: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
    ]
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4776)
        	... 11 more
     Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
    ]
        at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
        at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:7057)
        at com.websitebeaver.documentscanner.utils.ImageUtil.getImageFromFilePath(ImageUtil.kt:35)
        at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:80)
        at com.websitebeaver.documentscanner.DocumentScannerActivity$cameraUtil$1.invoke(DocumentScannerActivity.kt:67)
        at com.websitebeaver.documentscanner.utils.CameraUtil.startForResult$lambda-0(CameraUtil.kt:41)
        at com.websitebeaver.documentscanner.utils.CameraUtil.$r8$lambda$QtmUm3JcXlX2aa1YkJnrPoMUzS8(Unknown Source:0)
        at com.websitebeaver.documentscanner.utils.CameraUtil$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:647)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
        at android.app.Activity.dispatchActivityResult(Activity.java:8413)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
        	... 12 more**
I/Process: Sending signal. PID: 24319 SIG: 9
Disconnected from the target VM, address: 'localhost:60041', transport: 'socket'


I hope this is helpful.

**Comment by dmarcs** [comment] 2022-09-08 02:11
which device and Android version?

**Comment by brunobless** [comment] 2022-09-08 12:49
I have this behaviour on a "Samsung Galaxy S21" and "Samsung Galaxy S22" device.

Model: Samsung SM-G991B (Samung Galaxy S21)
Android version: 12
One UI version: 4.1

**Comment by dmarcs** [comment] 2022-11-06 20:25
fixed in https://github.com/WebsiteBeaver/capacitor-document-scanner/tree/1.0.1

https://github.com/WebsiteBeaver/android-document-scanner/commit/81420c8cdfb35b2a972dff4b6ec592bfb3e53604
An orientation change (portrait to landscape) causes the activity to restart which crashes the app.

**Closed by dmarcs** 2022-11-06 20:25 UTC
